version: '3'

services: 
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        container_name: es01
        environment:
            - node.name=es01
            - discovery.type=single-node
            - cluster.name=es-docker-cluster
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./es01:/var/lib/elasticsearch/data
        ports:
            - 9200:9200
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.11.2
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200"]'

    nginx:
         image: wesley/nginx-beats
         ports: 
            - 9000:80